POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Accept: application/json

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="campanhas.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./campanhas.xlsx
------WebKitFormBoundary--
